### ISSUE TITLE
Services execute alphabetically 

### ISSUE THREAD

**Issue by openPablo** [stacklio/stackl#224]
# Expected Result
Services execute in the order specified in the SAT
# Actual Result
Services execute in alphabetical order by service name
# Steps To Reproduce
Create SAT with two services, make the order in the SAT config file non alphabetical.
# Potential Causes, Fixes or Additional Information

**Comment by mieel** [comment]
To further illustrate why this is an issue:

We have 3 services: frontend, backend, database.
backend is dependent on database and will fail if the database is not ready.

By simply describing these services in the correct order, we expect them to be executed in that order.

Because the current state executes them alphabetically, we have to work around it by naming the services like `0_database`, `1_backend`, `2_frontend`.

But then we run into other issue when some FR expect the service to have a specific value (ansible role host pattern)
